apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amul-widget
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "120"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - widget.amulai.in
      secretName: amulai-in-tls
  rules:
    - host: widget.amulai.in
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: widget-web
                port:
                  number: 8080
