apiVersion: apps/v1
kind: Deployment
metadata:
  name: widget-web
  namespace: amul-prod
  labels:
    app.kubernetes.io/name: widget-web
    app.kubernetes.io/part-of: amul-widget
spec:
  replicas: 2
  selector:
    matchLabels:
      app: widget-web
  template:
    metadata:
      labels:
        app: widget-web
        app.kubernetes.io/name: widget-web
        app.kubernetes.io/part-of: amul-widget
    spec:
      imagePullSecrets:
        - name: regcred
      nodeSelector:
        role: backend
      containers:
        - name: widget-web
          image: registry.prod.amulai.in/widget-web:1bd2899
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /widget.js
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /widget.js
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
          resources:
            requests:
              cpu: 50m
              memory: 32Mi
            limits:
              cpu: 250m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: widget-web
  namespace: amul-prod
  labels:
    app.kubernetes.io/name: widget-web
    app.kubernetes.io/part-of: amul-widget
spec:
  selector:
    app: widget-web
  ports:
    - port: 8080
      targetPort: 8080
